### PR TITLE
Wayland support

### PR DESCRIPTION
**Pull request by stianfo**
Very simple change that exposes the Wayland socket to support that out of the box.

### CODE REVIEW

**Comment by BigmenPixel0** [comment]
Hi. Wayland is not supported in the official Monero GUI binary. This is currently supported if compiled from source. Can you make a PR to the beta branch?

**Comment by stianfo** [comment]
Really? Could have sworn I got it to work locally, but it appears you are correct. Even though the lack of Wayland annoys me to no end, I guess FlatHub only deals with precompiled binaries, right?

**Comment by BigmenPixel0** [comment]
> I guess FlatHub only deals with precompiled binaries, right?

In FlatHub, it is very desirable to compile the program from source, I did this in the beta branch

> Could have sworn I got it to work locally, but it appears you are correct.

Did you run org.getmonero.Monero with `--env=QT_QPA_PLATFORM=wayland`?

**Comment by stianfo** [comment]
Ah, gotcha. I see now that it doesn't support it. I'll play around with it a little and open a PR on the beta branch and see if I can get it working.

**Pull request closed without merging**
